# Generated by Django 5.2 on 2025-05-09 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("model_api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient_detail",
            name="name",
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
